version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 55432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  #pgadmin:
  #  image: dpage/pgadmin4:latest
  #  container_name: pgadmin
  #  restart: always
  #  depends_on:
  #    - postgres
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: user@localhost.com
  #    PGADMIN_DEFAULT_PASSWORD: password
  #  ports:
  #    - 8080:80
  #  volumes:
  #    - ./data/pgadmin:/var/lib/pgadmin      
  api:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - postgres